# Pipeline Configuration

# Path to the folder containing CCS bam files
CCS_FOLDER: /path/to/CCS/folder

# Path to the folder containing the subreads bam files
SUBREADS_FOLDER: /path/to/subreads/folder

# Path to barcode fasta file used for demultiplexing
BARCODES: /path/to/barcodes.fasta  

# params for individual stages
# to disable a stage, remove its parameters
STAGE_PARAMS:
  CCS_AMPLICON:
    min-ccs-length: 6000
    max-ccs-length: 7000
    min-ccs-passes: 1
    min-ccs-qual: 0.95
    max-homopolymer: 2
    trim-ends: 0
    tsne-iterations: 5000
    tsne-rate: 50
    cluster-percentile: 10
    cluster-inflation: 1.4
    cluster-size-threshold: 0.2
    max-cluster-size: 300
    consensus-fraction: 0.25
    min-haplotype-molecules: 10
    min-variant-qual: 50
    max-phasing-seqs: 100
    forward-primer: GCAGTCGAACATGTAGCTGACTCAGGTCACATGGCAGCTGCCATACAATCCACCTG
    reverse-primer: TGGATCACTTGTGCAAGCATCACATCGTAGCGACTGAGCCCTGGGAGGTAGGTAG
    max-primer-dist: 5

