# Pipeline Configuration

# Path to the folder containing CCS bam files
CCS_FOLDER: /path/to/CCS/folder

# Path to the folder containing the subreads bam files
SUBREADS_FOLDER: /path/to/subreads/folder

# Path to barcode fasta file used for demultiplexing
BARCODES: /path/to/barcodes.fasta  

# Path to the genome fasta file to be used for mapping/alignment
# The location of this file should be writable so that indexes can be created
GENOME: /path/to/genome.fasta

# params for individual stages
# to disable a stage, remove its parameters
STAGE_PARAMS:
  CCS_AMPLICON:
    min-ccs-length: 6000
    max-ccs-length: 7000
    min-ccs-passes: 1
    min-ccs-qual: 0.98
    max-homopolymer: 2
    tsne-iterations: 5000
    tsne-rate: 50
    cluster-percentile: 80
    cluster-inflation: 1.4
    cluster-size-threshold: 0.2
    cluster-fraction: 0.8
    consensus-fraction: 0.51
    min-haplotype-molecules: 10
    min-variant-qual: 50
